### ISSUE TITLE
unable to resolve dependencies

### ISSUE THREAD

**Issue by matesio** [snowplow/scala-weather#22]
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.scala-lang#scala-library;2.10: not found
[warn] 	:: org.scala-lang#scala-reflect;2.10: not found
[warn] 	:: com.snowplowanalytics#scala-weather_2.10;0.1.0: not found
[warn] 	:: org.scala-lang#scala-compiler;2.10: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.scala-lang:scala-library:2.10 ((sbt.Classpaths) Defaults.scala#L1293)
[warn] 		  +- org.scalamacros:quasiquotes_2.10:2.1.0
[warn] 		  +- org.typelevel:macro-compat_2.10:1.1.1
[warn] 		  +- com.github.mpilquist:simulacrum_2.10:0.10.0
[warn] 		  +- org.typelevel:cats-macros_2.10:0.9.0 (/home/rosailstax/Desktop/openWeatherMap/build.sbt#L29-30)
[warn] 		  +- org.typelevel:cats-core_2.10:0.9.0 (/home/rosailstax/Desktop/openWeatherMap/build.sbt#L29-30)
[warn] 		  +- org.typelevel:cats-jvm_2.10:0.9.0 (/home/rosailstax/Desktop/openWeatherMap/build.sbt#L29-30)
[warn] 		  +- org.typelevel:cats_2.10:0.9.0 (/home/rosailstax/Desktop/openWeatherMap/build.sbt#L29-30)
[warn] 		  +- ch.epfl.scala:hello-world_2.10:1.0
[warn] 		org.scala-lang:scala-reflect:2.10
[warn] 		  +- org.scalamacros:quasiquotes_2.10:2.1.0
[warn] 		  +- org.typelevel:macro-compat_2.10:1.1.1
[warn] 		  +- com.github.mpilquist:simulacrum_2.10:0.10.0
[warn] 		  +- org.typelevel:cats-macros_2.10:0.9.0 (/home/rosailstax/Desktop/openWeatherMap/build.sbt#L29-30)
[warn] 		  +- org.typelevel:cats-core_2.10:0.9.0 (/home/rosailstax/Desktop/openWeatherMap/build.sbt#L29-30)
[warn] 		  +- org.typelevel:cats-jvm_2.10:0.9.0 (/home/rosailstax/Desktop/openWeatherMap/build.sbt#L29-30)
[warn] 		  +- org.typelevel:cats_2.10:0.9.0 (/home/rosailstax/Desktop/openWeatherMap/build.sbt#L29-30)
[warn] 		  +- ch.epfl.scala:hello-world_2.10:1.0
[warn] 		com.snowplowanalytics:scala-weather_2.10:0.1.0 (/home/rosailstax/Desktop/openWeatherMap/build.sbt#L29-30)
[warn] 		  +- ch.epfl.scala:hello-world_2.10:1.0
[warn] 		org.scala-lang:scala-compiler:2.10
[warn] 		  +- ch.epfl.scala:hello-world_2.10:1.0
sbt.ResolveException: unresolved dependency: org.scala-lang#scala-library;2.10: not found
unresolved dependency: org.scala-lang#scala-reflect;2.10: not found
unresolved dependency: com.snowplowanalytics#scala-weather_2.10;0.1.0: not found
unresolved dependency: org.scala-lang#scala-compiler;2.10: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
	at sbt.IvySbt.withIvy(Ivy.scala:128)
	at sbt.IvySbt.withIvy(Ivy.scala:125)
	at sbt.IvySbt$Module.withModule(Ivy.scala:156)
	at sbt.IvyActions$.updateEither(IvyActions.scala:168)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1481)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1477)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$121.apply(Defaults.scala:1512)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$121.apply(Defaults.scala:1510)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1515)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1509)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1532)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1459)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1411)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
[error] (*:update) sbt.ResolveException: unresolved dependency: org.scala-lang#scala-library;2.10: not found
[error] unresolved dependency: org.scala-lang#scala-reflect;2.10: not found
[error] unresolved dependency: com.snowplowanalytics#scala-weather_2.10;0.1.0: not found
[error] unresolved dependency: org.scala-lang#scala-compiler;2.10: not found
[error] Total time: 46 s, completed Jul 18, 2017 7:11:11 PM

**Comment by BenFradet** [comment]
Did you add the following resolver:

```scala
val snowplowRepo = "Snowplow Analytics" at "http://maven.snplow.com/releases/"
```

Also the latest release is 0.2.0.

**Comment by matesio** [comment]
i have added these as given in documentation

val snowplowRepo = "Snowplow Analytics" at "http://maven.snplow.com/releases/"
val oldTwitterRepo  = "Twitter Maven Repo" at "http://maven.twttr.com/"
val newTwitterRepo = "Sonatype" at "https://oss.sonatype.org/content/repositories/releases"

**Comment by BenFradet** [comment]
How are you adding your resolvers, because:

>sbt.ResolveException: unresolved dependency: org.scala-lang#scala-library;2.10: not found

is not normal

**Comment by matesio** [comment]
here is my build.sbt file, 

scalaVersion := "2.11.8"
name := "openweather"
organization := "rosail.scala"
version := "1.0"
val snowplowRepo = "Snowplow Analytics" at "http://maven.snplow.com/releases/"
val oldTwitterRepo  = "Twitter Maven Repo" at "http://maven.twttr.com/"
val newTwitterRepo = "Sonatype" at "https://oss.sonatype.org/content/repositories/releases"

libraryDependencies ++= Seq("org.typelevel" %% "cats" % "0.9.0",
"com.snowplowanalytics" %% "scala-weather"  % "0.1.0"
)


please tell me where i am wrong

**Comment by matesio** [comment]
here is the latest log 
[info] Resolving jline#jline;2.12.1 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.snowplowanalytics#scala-weather_2.11;0.1.0: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.snowplowanalytics:scala-weather_2.11:0.1.0 (/home/rosailstax/Desktop/openWeatherMap/build.sbt#L28-31)
[warn] 		  +- ch.epfl.scala:hello-world_2.11:1.0
sbt.ResolveException: unresolved dependency: com.snowplowanalytics#scala-weather_2.11;0.1.0: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
	at sbt.IvySbt.withIvy(Ivy.scala:128)
	at sbt.IvySbt.withIvy(Ivy.scala:125)
	at sbt.IvySbt$Module.withModule(Ivy.scala:156)
	at sbt.IvyActions$.updateEither(IvyActions.scala:168)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1481)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1477)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$121.apply(Defaults.scala:1512)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$121.apply(Defaults.scala:1510)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1515)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1509)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1532)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1459)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1411)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
[error] (*:update) sbt.ResolveException: unresolved dependency: com.snowplowanalytics#scala-weather_2.11;0.1.0: not found
[error] Total time: 3 s, completed Jul 18, 2017 8:09:30 PM

**Comment by BenFradet** [comment]
you're still using 0.1.0

**Comment by matesio** [comment]
what is your latest version ? 
 i have already mentioned , i have also used 
 "com.snowplowanalytics" %% "scala-weather" % "0.2.0"

but it did not work can you please update documentation to latest version and do share correct dependeny

**Comment by BenFradet** [comment]
"com.snowplowanalytics" %% "scala-weather" % "0.2.0"

is the correct dependency which I can get without any issues, your last message contains

> sbt.ResolveException: unresolved dependency: com.snowplowanalytics#scala-weather_2.11;0.1.0: not found

**Comment by matesio** [comment]
still same 
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
[error] (*:update) sbt.ResolveException: unresolved dependency: com.snowplowanalytics#scala-weather_2.11;0.2.0: not found
[error] Total time: 3 s, completed Jul 18, 2017 8:33:43 PM

**Comment by BenFradet** [comment]
I'm not able to reproduce your issue, how are you adding your resolvers?

**Comment by chuwy** [comment]
@matesio your `build.sbt` should look like following:

```scala
scalaVersion := "2.11.8"
name := "openweather"
organization := "rosail"
version := "1.0"
val snowplowRepo = "Snowplow Analytics" at "http://maven.snplow.com/releases/"
val oldTwitterRepo = "Twitter Maven Repo" at "http://maven.twttr.com/"
val newTwitterRepo = "Sonatype" at "https://oss.sonatype.org/content/repositories/releases"

resolvers ++= Seq(snowplowRepo, oldTwitterRepo, newTwitterRepo) 

libraryDependencies ++= Seq(
  "org.typelevel" %% "cats" % "0.9.0",
  "com.snowplowanalytics" %% "scala-weather" % "0.2.0"
)
```

Resolvers should be enabled, not just declared. Also avoid using `scala` in organization or package name.

**Comment by matesio** [comment]
yeah  it worked, thanks  alot  , i have spent whole day in resolving
